<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Akses extends CI_Controller
{
    function __construct()
    {
       parent::__construct();
        is_login();
        is_boleh();
       $this->load->model('User_model','um');
       $this->load->model('Akses_model');
       $this->load->library('form_validation');        
	   $this->load->library('datatables');
    }

    public function index()
    {
        $data['judul'] = 'Hak Akses';
        $this->load->view('templates/header', $data);
        $this->load->view('akses/user_dapat_rule_list');
    } 

    public function oke(){
        is_boleh();
    }
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Akses_model->json();
    }

    public function read($id) 
    {
        $row = $this->Akses_model->get_by_id($id);
        if ($row) {
            $data = array(
    		'id' => $row->id,
    		'user_id' => $row->user_id,
    		'rule_id' => $row->rule_id,
	    );
            $this->load->view('akses/user_dapat_rule_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('akses'));
        }
    }

    public function create() 
    {
        
        $data = array(
            'button' => 'Tambah hak akses',
            'action' => site_url('akses/create_action'),
    	    'id' => set_value('id'),
    	    'user_id' => set_value('user_id'),
    	    'rule_id' => set_value('rule_id'),
    	);
        $data['judul'] = 'Hak Akses';

        $this->db->select('id_user, nama, email');
        $data['user'] = $this->db->get('user_data')->result_array();
        $data['rule'] = $this->db->get_where('user_rule',['id_rule > ' => 1])->result_array();

        $this->load->view('templates/header', $data);
        $this->load->view('akses/user_dapat_rule_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
    		$user_ids = $this->input->post('user',TRUE);
    		$rule_ids = $this->input->post('rule',TRUE);

            foreach ($user_ids as $user) {
                foreach ($rule_ids as $rule) {
                    $data ['user_id'] = $user;
                    $data ['rule_id'] = $rule;
                    $ada = $this->Akses_model->get_by_data($data);
                    if ($ada < 1) {
                        $this->Akses_model->insert($data);
                    }
                }
            }

            $this->session->set_flashdata('message', 'Tambah data berhasil');
            redirect(site_url('akses'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Akses_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('akses/update_action'),
        		'id' => set_value('id', $row->id),
        		'user_id' => set_value('user_id', $row->user_id),
        		'rule_id' => set_value('rule_id', $row->rule_id),
        	);
            $this->load->view('akses/user_dapat_rule_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('akses'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'user_id' => $this->input->post('user',TRUE),
		'rule_id' => $this->input->post('rule',TRUE),
	    );

            // $this->Akses_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('akses'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Akses_model->get_by_id($id);

        if ($row) {
            $this->Akses_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('akses'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('akses'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('user[]', 'user', 'trim|required');
	$this->form_validation->set_rules('rule[]', 'rule', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Akses.php */
/* Location: ./application/controllers/Akses.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-08 02:32:06 */
/* http://harviacode.com */