<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Psb_model extends CI_Model
{

    public $table = 'p_data_awal';
    public $id = 'id_data_awal';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_data_awal,nama,nik,nisn,alamat_pengenal,npsn_asal,desa_id,nohp,proses,ijasah,skhu,kk,akte,kartu,keuangan,asesment,verf_keuangan');
        $this->datatables->from('p_data_awal');
        //add this line for join
        //$this->datatables->join('table2', 'p_data_awal.field = table2.field');
        $this->datatables->add_column('action', '<a class="d-flex flex-column mb-4 klik-lama" href="'.base_url('psb/read/$1').'"><i class="far fa-list-alt"></i></a><hr>'.anchor(site_url('psb/#'/*'psb/delete/$1'*/),'<i class="far fa-trash-alt text-danger"></i>','onclick="javasciprt: return confirm(\'Yakin mau menghapus semua data $2 ?\')"'), 'id_data_awal, nama');
        return $this->datatables->generate();
    }

    function tampilDesa($id_desa)
    {
        $stringQ = " SELECT d.`name` AS ds, k.`name` AS kec , b.`name` AS kab, v.`name` AS prop
                FROM i_desa d JOIN i_kecamatan k
                ON k.`id` = d.`kecamatan_id` JOIN i_kabkot b
                ON k.`kabkot_id` = b.`id` JOIN i_propinsi v
                ON v.`id` = b.`propinsi_id` WHERE d.`id` = '$id_desa' ";
        $hasil =  $this->db->query($stringQ)->row_array();
        
        if ($hasil != NULL){
            
            return $hasil;

        }else{
            
            $tingkat = [
                13 => 'ds',
                8 => 'kec',
                5 => 'kab',
                2 => 'prop',
            ];
            
            foreach ($tingkat as $tk => $val) {
                $kode = substr($id_desa, 0, $tk);

                $this->db->select('nama');
                $data = $this->db->get_where('wilayah_2020', ['kode'=>$kode])->row_array();
                $hasil [$val] = $data['nama'] ;
            }

            return $hasil;
        }
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_data_awal', $q);
    	$this->db->or_like('nama', $q);
    	$this->db->or_like('nik', $q);
    	$this->db->or_like('nisn', $q);
    	$this->db->or_like('alamat_pengenal', $q);
    	$this->db->or_like('npsn_asal', $q);
    	$this->db->or_like('desa_id', $q);
    	$this->db->or_like('nohp', $q);
    	$this->db->or_like('proses', $q);
    	$this->db->or_like('ijasah', $q);
    	$this->db->or_like('skhu', $q);
    	$this->db->or_like('kk', $q);
    	$this->db->or_like('akte', $q);
    	$this->db->or_like('kartu', $q);
    	$this->db->or_like('keuangan', $q);
    	$this->db->or_like('asesment', $q);
    	$this->db->or_like('verf_keuangan', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_data_awal', $q);
    	$this->db->or_like('nama', $q);
    	$this->db->or_like('nik', $q);
    	$this->db->or_like('nisn', $q);
    	$this->db->or_like('alamat_pengenal', $q);
    	$this->db->or_like('npsn_asal', $q);
    	$this->db->or_like('desa_id', $q);
    	$this->db->or_like('nohp', $q);
    	$this->db->or_like('proses', $q);
    	$this->db->or_like('ijasah', $q);
    	$this->db->or_like('skhu', $q);
    	$this->db->or_like('kk', $q);
    	$this->db->or_like('akte', $q);
    	$this->db->or_like('kartu', $q);
    	$this->db->or_like('keuangan', $q);
    	$this->db->or_like('asesment', $q);
    	$this->db->or_like('verf_keuangan', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);

        $this->db->where('data_awal_id', $id);
        $this->db->delete('p_pendaftaran');

        $this->db->where('data_awal_id', $id);
        $this->db->delete('p_wali_pendaftaran');
    }

}

/* End of file Psb_model.php */
/* Location: ./application/models/Psb_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-06 02:19:16 */
/* http://harviacode.com */